myshell: esh.o lck.o cprt.o lineCount.o prevStr.o quickSet.o
	gcc -o myshell esh.o lck.o cprt.o lineCount.o prevStr.o quickSet.o
esh.o: esh.c
	gcc -c esh.c
lck.o: lck.c
	gcc -c lck.c
cprt.o: cprt.c
	gcc -c cprt.c
lineCount.o: lineCount.c
	gcc -c lineCount.c
prevStr.o: prevStr.c
	gcc -c prevStr.c
quickSet.o: quickSet.c
	gcc -c quickSet.c
