myshell: eesh.o lck.o cprt.o lineCount.o prevStr.o
	gcc -o myshell eesh.o lck.o cprt.o lineCount.o prevStr.o
esh.o: eesh.c
	gcc -c eesh.c
lck.o: lck.c
	gcc -c lck.c
cprt.o: cprt.c
	gcc -c cprt.c
lineCount.o: lineCount.c
	gcc -c lineCount.c
prevStr.o: prevStr.c
	gcc -c prevStr.c
